# Generated by Django 4.1.3 on 2022-12-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="additional_information",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="mobile_contact",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
    ]
