# Generated by Django 4.1.4 on 2022-12-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_bodypart_remove_userprofile_additional_information_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("hobbies", models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name="Hospital",
        ),
        migrations.DeleteModel(
            name="userProfile",
        ),
        migrations.DeleteModel(
            name="x",
        ),
        migrations.AddField(
            model_name="bodypart",
            name="bodyPart",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bodypart",
            name="products",
            field=models.ManyToManyField(
                default="none", null=True, related_name="products", to="medical.product"
            ),
        ),
    ]
