# Generated by Django 4.1.4 on 2022-12-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_tt_delete_hospital_delete_userprofile_delete_x_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tt",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
