# Generated by Django 4.1.4 on 2022-12-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0010_good"),
    ]

    operations = [
        migrations.RenameField(
            model_name="good",
            old_name="tax",
            new_name="tax_id",
        ),
    ]
