# Generated by Django 4.1.4 on 2022-12-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0013_rename_tax_test_tax_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hospital",
        ),
    ]
