# Generated by Django 4.1.4 on 2022-12-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0017_alter_hospital_taxid_hospital2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital2",
            name="bankaccount",
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name="hospital2",
            name="name",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="hospital2",
            name="routing",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AlterField(
            model_name="hospital2",
            name="taxid",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="tax_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
