# Generated by Django 4.1.4 on 2022-12-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0018_alter_hospital2_bankaccount_alter_hospital2_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital2",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hospital2",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospital2",
            name="approved_by",
            field=models.CharField(blank=True, default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="bankaccount",
            field=models.CharField(default="", max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="routing",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="street",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="taxid",
            field=models.CharField(default="", max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="zip",
            field=models.TextField(default="", max_length=5),
        ),
    ]
