# Generated by Django 4.1.4 on 2022-12-29 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0019_hospital2_approved_hospital2_approved_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BodyPart",
        ),
    ]
