# Generated by Django 4.1.4 on 2022-12-29 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("quantity", models.PositiveIntegerField(null=True)),
                ("category", models.CharField(max_length=50, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "manufacturer",
                    models.CharField(default="", max_length=30, null=True),
                ),
                ("UPC", models.CharField(default="", max_length=25, null=True)),
                ("SKU", models.CharField(max_length=30, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(default="", max_length=50, null=True)),
                ("bodyparts", models.JSONField()),
                (
                    "products",
                    models.ManyToManyField(
                        default="none",
                        null=True,
                        related_name="products",
                        to="Products.product",
                    ),
                ),
            ],
        ),
    ]
