# Generated by Django 4.0.7 on 2022-10-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmthrough',
            name='n',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
