# Generated by Django 4.0.7 on 2022-10-07 00:51

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_remove_dmthrough_n_remove_notification_stop_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='to_notify_friends',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circle',
            name='to_notify_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
